apiVersion: v1
kind: Service
metadata:
  name: socialsphere-api
  namespace: social-media
  labels:
    app.kubernetes.io/name: socialsphere
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: socialsphere
    app.kubernetes.io/component: api
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
