apiVersion: v1
kind: ConfigMap
metadata:
  name: socialsphere-web-config
  namespace: social-media
data:
  NODE_ENV: "production"
  HOSTNAME: "0.0.0.0"
  PORT: "3000"
  NEXT_PUBLIC_API_URL: "/"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ""
