services:
  api:
    image: socialsphere-api:next-fastapi
    build:
      context: ./api
    container_name: socialsphere-api
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      socialsphere-network:
        aliases:
          - api

  web:
    image: socialsphere-web:next-fastapi
    build:
      context: ./web
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    container_name: socialsphere-web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - socialsphere-network

networks:
  socialsphere-network:
